eatdsui:
  users:
    #user@zanini.com
    526fcbfc-6b3c-414d-853d-83d15dbc7629:
      customer: ZANINI
      licences:
        - Ebin
        - Ebdx
      roles:
        - ROLE_ADMIN
        - ROLE_USER
 