spring:
  profiles:
    include: npro,npro2,zanini,sptd,company
eatdsui:
  users:
    #ebfx
    5s83elqeb08ubrlnpbn6j85b0l:
      customer: EAT_INTERNAL_APP
      licences:
        - Ebin
        - Ebdx
      roles:
        - ROLE_ADMIN
        - ROLE_USER
    #ebinfx
    14p6fhojcbc5n5mr9bvhlqfs41:
      customer: EAT_INTERNAL_APP
      licences:
        - Ebin
        - Ebdx
      roles:
        - ROLE_ADMIN
        - ROLE_USER
    #ebdx
    6je9m11fb4vousaijc7qvr7unj:
      customer: EAT_INTERNAL_APP
      licences:
        - Ebin
        - Ebdx
      roles:
        - ROLE_ADMIN
        - ROLE_USER