dsui:
  users:
    #user@npro.com
    ea7ecbba-a9a8-4801-9bc1-d13e04b909ef:
      customer: NPRO
      licences:
        - Ebfx
        - Ebdx
      roles:
        - ROLE_ADMIN
        - ROLE_USER
    ea9ecbba-a9a8-4801-9bc1-d13e04b909ef:
      customer: SPTD
      licences:
        - EssSuite
      roles:
        - ROLE_ADMIN
